# Configuration for CI build at https://travis-ci.org/cbeams/libjava

language: java

jdk:
  - oraclejdk8

env:
  global:
  - secure: "Gl96694EyiJebRJo3xrdY3gOl4bB/7ZVSBmSAzYKvwkNne2FY0udctM8vczGuT7kvEfX7GW5BRF9VTCTE5qorMaZFIauNTfJ9XAqRuEhVn4eqZaYZfC+QzjEsf6SNbEC6x0AVWK5GvfaDzAWt1HrByy4AXy2gfifEiHaAeS1Fj8="

after_success:
- .travis/publish-javadoc.sh
