/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cbeams' at '3/23/14 8:57 AM' with Gradle 1.11
 *
 * @author cbeams, @date 3/23/14 8:57 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
